# Generated by Django 4.0.2 on 2022-02-03 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_city_house_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('main_photo', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='images')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='houses.house')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
