# Generated by Django 4.0.2 on 2022-02-05 18:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_city_zip_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseDetails',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('house', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='houses.house')),
                ('rooms', models.IntegerField(default=0)),
                ('qm', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)])),
                ('beds', models.IntegerField(default=0)),
                ('balcony', models.BooleanField(default=False)),
                ('bathrooms', models.IntegerField(default=0)),
                ('kitchen', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='house',
            name='qm',
        ),
    ]
